### ISSUE TITLE
Not setting Payment Limit in PayPal Express

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-failed-payment-limit#4]
There is an issue where it's not setting a number of failed payments within the payment gateway - https://wordpress.org/support/topic/bug-when-user-cancell-recurring-subscription-at-paypal/

Image for reference - https://imgur.com/BzQzgWy

**Comment by zeusdesignco** [comment]
we have the same issue, any updates on this?

**Comment by mircobabini** [comment]
I see that I'm not alone here. @andrewlimaza it's happening to me on a live site about 15 times a day, having issue with this one. I can share you a complete log, references, screenshots and full access to a website facing the issue.

If you want to go deeper into it, I think it's the time to do it :) We can't live with this bug anymore, 2 hours of customer support per day because of this.

Hit me up on slack please.

**Comment by mircobabini** [comment]
Also, why don't you also cancel the subscription at Gateway? This is causing issues because:
1) You cancel the membership keeping the subscription active on Gateway
2) The user make a new subscription
3) The old subscription succed renewing making double payments.

**Comment by mircobabini** [comment]
`MAXFAILEDPAYMENTS=1` is in place for every new PayPal Express subscription since PMPro 2.5.2.

**This issue can be closed.**
